This is makeindex, version 2.15 [TeX Live 2017] (kpathsea + Thai support).
Scanning style file ./SRS.ist.............................done (29 attributes redefined, 0 ignored).
Scanning input file SRS.acn....done (41 entries accepted, 0 rejected).
Sorting entries....done (231 comparisons).
Generating output file SRS.acr....done (49 lines written, 0 warnings).
Output written in SRS.acr.
Transcript written in SRS.alg.
